# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0d40c784162210a9dc31d0aa51883f7"
name = "mhf-b2b-shipping-discount"
handle = "mhf-b2b-shipping-discount"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-f1beed7b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,write_delivery_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
